### PR TITLE
Adding support for optional X509 certificats.

### PR DESCRIPTION
**Pull request by jonathan**
I'm working with a client who needs who needs the optional X509Certificate element in their signatures. Added support to add that element given a certificate is given along with a signing key.

### CODE REVIEW

**Comment by RafaelFerraro** [comment]
Hello @benoist I've looking for this pull request and the comments a time ago.
I have a bit of experience with xml signatures and I'm very interesting in contribute with this project!

When you say to create separated builder classes, your are proposing to create another responsibility to the lib, right ? This way, the lib will not only set the values for predefined tags, but will also create all Signature tags, if this doesn't exist, I'm right?

**Comment by benoist** [comment]
HI @RafaelFerraro thank you for your interest!

Yeah it would be another responsibility. It would create everything required to sign an XML document. In libsaml we already have a lot of the elements defined, we should probably be able to copy most of it and move it in this gem. Later on I expected the builders to be removed from libsaml and just use the builders from this gem.

**Comment by RafaelFerraro** [comment]
Thank you for your response! 

Perfect! I don't have much free time to contribute, but I will make an effort to accomplish this task.
I will make a fork on @jonathan branch to start, what do you think @benoist and @jonathan ? Thus, I take the X509 certificate support, alright ?

**Comment by benoist** [comment]
Yeah thats fine by me :-)

**Pull request closed without merging**
