### PR TITLE
Checking if node exists before removing

### PR DESCRIPTION
**Pull request by gabteles**
Hi, I've just added a checking before removing signature node.

### CODE REVIEW

**Comment by benoist** [comment]
Hi,

Can you explain the problem you ran into? Because the enveloped signature transform expects the signature in that location.

**Comment by gabteles** [comment]
Hello, it happens when I try to sign this XML below. Prettified for legibility, but tried to sign without line breaks or spaces between fields. 

Also, obfuscated some fields with sensitive informations:

```xml
<NFe xmlns="http://www.portalfiscal.inf.br/nfe">
  <infNFe Id="NFe11111111111111111111111111111111111111111111" versao="3.10">
    <ide>
      <cUF>53</cUF>
      <cNF>63298677</cNF>
      <natOp>VENDA</natOp>
      <indPag>0</indPag>
      <mod>65</mod>
      <serie>19</serie>
      <nNF>3</nNF>
      <dhEmi>2017-02-16T11:09:04-02:00</dhEmi>
      <tpNF>1</tpNF>
      <idDest>1</idDest>
      <cMunFG>5300108</cMunFG>
      <tpImp>4</tpImp>
      <tpEmis>1</tpEmis>
      <cDV>0</cDV>
      <tpAmb>2</tpAmb>
      <finNFe>1</finNFe>
      <indFinal>1</indFinal>
      <indPres>1</indPres>
      <procEmi>0</procEmi>
      <verProc>0.0.1a</verProc>
    </ide>
    <emit>
      <CNPJ>11111111000111</CNPJ>
      <xNome>Obfuscated String</xNome>
      <xFant>Obfuscated String</xFant>
      <enderEmit>
        <xLgr>Obfuscated String</xLgr>
        <nro>0</nro>
        <xCpl>Obfuscated String</xCpl>
        <xBairro>Obfuscated String</xBairro>
        <cMun>5300108</cMun>
        <xMun>BRASILIA</xMun>
        <UF>DF</UF>
        <CEP>70000111</CEP>
        <cPais>1058</cPais>
        <xPais>BRASIL</xPais>
        <fone>6199999999</fone>
      </enderEmit>
      <IE>1111111111111</IE>
      <IM>1111111111111</IM>
      <CRT>1</CRT>
    </emit>
    <det nItem="1">
      <prod>
        <cProd>1694</cProd>
        <cEAN/>
        <xProd>NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>
        <NCM>00000000</NCM>
        <CFOP>5102</CFOP>
        <uCom>UND</uCom>
        <qCom>1.0</qCom>
        <vUnCom>2000.00</vUnCom>
        <vProd>2000.00</vProd>
        <cEANTrib/>
        <uTrib>UND</uTrib>
        <qTrib>1.0</qTrib>
        <vUnTrib>2000.00</vUnTrib>
        <indTot>1</indTot>
      </prod>
      <imposto>
        <ICMS>
          <ICMSSN102>
            <orig>0</orig>
            <CSOSN>102</CSOSN>
          </ICMSSN102>
        </ICMS>
      </imposto>
    </det>
    <total>
      <ICMSTot>
        <vBC>0.00</vBC>
        <vICMS>0.00</vICMS>
        <vICMSDeson>0.00</vICMSDeson>
        <vBCST>0.00</vBCST>
        <vST>0.00</vST>
        <vProd>2000.00</vProd>
        <vFrete>0.00</vFrete>
        <vSeg>0.00</vSeg>
        <vDesc>0.00</vDesc>
        <vII>0.00</vII>
        <vIPI>0.00</vIPI>
        <vPIS>0.00</vPIS>
        <vCOFINS>0.00</vCOFINS>
        <vOutro>0.00</vOutro>
        <vNF>2000.00</vNF>
      </ICMSTot>
    </total>
    <transp>
      <modFrete>9</modFrete>
    </transp>
    <pag>
      <tPag>01</tPag>
      <vPag>2000.00</vPag>
    </pag>
  </infNFe>
  <infNFeSupl>
    <qrCode><![CDATA[ obfuscated url string ]]></qrCode>
  </infNFeSupl>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
      <Reference URI="#NFe11111111111111111111111111111111111111111111">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
          <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
        <DigestValue/>
      </Reference>
    </SignedInfo>
    <SignatureValue/>
    <KeyInfo>
      <X509Data>
        <X509Certificate>Valid Public Certificate</X509Certificate>
      </X509Data>
    </KeyInfo>
  </Signature>
</NFe>
``` 

Tried to sign this way:

```ruby
unsigned_xml = "xml above, omitted for brevity" 
private_key = OpenSSL::PKey::RSA.new("Valid Private Key String")

document = Nokogiri::XML::Document.parse(unsigned_xml) {|config| config.strict.noblanks }
unsigned_document = Xmldsig::SignedDocument.new(document, id_attr: 'Id')
signed_xml = unsigned_document.sign(private_key, false)
```

**Comment by benoist** [comment]
If you use the envelope transform the signature needs to be a child of the referenced node.
If the signature location needs to be on the outside of the node to sign, you have to remove the enveloped transform.

**Comment by benoist** [comment]
Any luck?

**Pull request closed without merging**
